// Per-vertical marketing copy, keyed by slug. AUTO-GENERATED by the Koemori
// content workflows (copy + quality + call-scripts), then hand-reviewed.
// Structural meta (icons, slugs, accent, demo agent, order) lives in ./verticals.js.
//
// Block shape: { badge, hero, missedCall, loopDescs[3], qualifyDesc,
//   why{h2Lead,h2Accent,stats[3]}, roi, surge, faq[6], seo, card, tradeOptions,
//   example{caller,outcome}, demo{turns[{speaker,text}],booked} }.
// Consumed by src/pages/Vertical.jsx, Services.jsx, Landing.jsx, TradeCallDemo.jsx.
// Roofing is intentionally absent — it keeps its bespoke page (src/pages/Home.jsx).

export const CONTENT = {
  "lawncare": {
    "badge": "Built for lawn-care pros · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while the mower's still running.",
      "sub": "Koemori is the AI receptionist built for lawn-care companies. It answers every call in under 3 seconds, sends you the lead, and lines up the appointment — so the homeowner who wants their yard cut this week books with you, not the next crew on the list."
    },
    "missedCall": {
      "value": "$1,800",
      "label": "season value of one missed weekly-mow lead",
      "yearLost": "$20,000+"
    },
    "loopDescs": [
      "Mower wide open, trimmer screaming, a client flagging you down at the curb — your phone's buried in the truck and there's no way you hear it ring. Koemori picks up in under 3 seconds in a natural voice and handles the caller like a real front-desk person would.",
      "The second the call ends, you get a text with the caller's name, number, property size, the service they asked for, and the full transcript. No phone number scrawled on a gas receipt — the lead's in your pocket before you fire up the next pass.",
      "Koemori asks when they want service and whether it's a one-time cut or a recurring weekly or biweekly plan, then drops it straight onto your calendar. The customer hangs up already booked, and you walk off this yard with the next one scheduled."
    ],
    "qualifyDesc": "Koemori asks the questions you'd ask yourself: how big the property is, what they need — mowing, edging, fertilization, aeration, or a full cleanup — whether it's a one-time visit or a weekly or biweekly recurring plan, and how soon they want it done. By the time you read the text, the lead is sorted, you can tell if it fits your route, and it's ready to schedule.",
    "why": {
      "h2Lead": "Built for lawn care.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$1,800",
          "body": "is what one weekly-mow client is worth across a single season — and they re-sign every year. Miss that first call and you didn't lose one cut, you lost the whole route."
        },
        {
          "stat": "26 cuts",
          "body": "a weekly customer books over a season. The crew that answers the very first call locks in all 26 — plus the fertilization and aeration add-ons and every renewal after. Speed on the phone is recurring revenue."
        },
        {
          "stat": "<3s",
          "body": "to answer every call — even when you're three yards deep, ear protection on, and your phone's in the cup holder of a running truck."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 35,
      "missedPct": 50,
      "avgJob": 450,
      "avgJobMin": 150,
      "avgJobMax": 2000,
      "blurb": "Every call you can't grab on the mower is a customer the next crew picks up instead — and in lawn care that's not one cut, it's a whole season of recurring revenue. See what those missed calls are quietly costing you each year."
    },
    "surge": {
      "badge": "Spring rush · Always on",
      "h2Lead": "When the grass takes off,",
      "h2Accent": "so does the phone.",
      "body": "The first warm week, the grass jumps and every homeowner in town wants on a route the same day — and they sign with the crew that answers first. You're slammed in the field dawn to dusk, which is exactly when the phone rings most. Koemori catches every one of those calls and locks in the recurring clients while you're heads-down mowing.",
      "bigStat": "85%",
      "bigStatSub": "of a lawn-care company's new accounts are won during the spring and early-summer growth surge",
      "cards": [
        {
          "stat": "3x",
          "label": "Call volume in spring",
          "sub": "Inbound calls spike the week the grass starts growing"
        },
        {
          "stat": "0",
          "label": "Calls to voicemail",
          "sub": "Every ring gets a real answer, not a recording"
        },
        {
          "stat": "24/7",
          "label": "After-hours coverage",
          "sub": "Catches evening and weekend callers lining up their season"
        },
        {
          "stat": "100%",
          "label": "Leads texted to you",
          "sub": "Name, property size, and service in your pocket instantly"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for lawn-care and lawn-maintenance businesses. It answers your inbound calls in a natural human voice, captures every lead, and books appointments on your calendar. It's made for owner-operators and growing crews who are out cutting all day and can't get to the phone."
      },
      {
        "q": "How does it work for a lawn-care business?",
        "a": "When a customer calls, Koemori answers in under 3 seconds and talks to them like your front desk would. It asks about their property size, the service they want, and whether it's a one-time cut or a recurring weekly or biweekly plan, then books a time on your calendar. The instant the call ends, you get a text with the lead's name, number, and the full transcript."
      },
      {
        "q": "Can it sign up recurring customers, not just one-time cuts?",
        "a": "Yes — and that's where it pays for itself. Koemori asks whether the caller wants a single visit or a recurring plan, captures how often they want service, and books the first appointment. A weekly mow client is worth thousands across a season and renews every year, so catching that one call while you're on the mower is the difference between a season of revenue and a missed ring."
      },
      {
        "q": "Does it sound robotic?",
        "a": "No. Koemori speaks in a natural, warm voice that sounds like a real person picking up your phone. Most callers never realize they're talking to AI — they just feel like they reached a company that answers and takes care of them."
      },
      {
        "q": "Do I have to change my phone number or setup?",
        "a": "Not at all. You keep your existing number and simply forward your calls to Koemori — it takes a few minutes to set up. Nothing changes for your customers; they call the same number they always have, and now someone always answers."
      },
      {
        "q": "What makes it specific to lawn care?",
        "a": "Koemori is tuned for the way lawn-care customers actually talk. It knows to ask about property size, mow frequency, recurring plans, and seasonal work like fertilization, aeration, and cleanups. It's not a generic answering service — it speaks your trade, so the leads it sends you are ready to drop onto a route."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Lawn Care Companies",
      "description": "Koemori answers every lawn-care call in under 3 seconds, texts you the lead, and books the appointment — so the homeowner who wants their yard cut this week signs with you, not the next crew."
    },
    "card": {
      "blurb": "The AI receptionist for lawn-care pros — answers every call on the mower, texts you the lead, and locks in the recurring route.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "residential lawn care",
      "commercial grounds maintenance",
      "fertilization & weed treatment",
      "aeration & overseeding",
      "seasonal cleanups"
    ],
    "example": {
      "caller": "Hey, my grass is getting out of hand and I want to get on a regular every-other-week mowing schedule — can someone come out and give me a price this week?",
      "outcome": "Booked a recurring estimate."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Green Valley Lawn Care, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, yeah, I'm looking to get my yard mowed regularly. Wanted to get a quote."
        },
        {
          "speaker": "ai",
          "text": "Happy to help with that. About how big is the property, and how often were you thinking?"
        },
        {
          "speaker": "caller",
          "text": "It's about a quarter acre. Probably every two weeks."
        },
        {
          "speaker": "ai",
          "text": "Got it, quarter acre, biweekly. I'll set up a quick on-site estimate so we can give you an exact price."
        },
        {
          "speaker": "caller",
          "text": "That works. When can someone come out?"
        },
        {
          "speaker": "ai",
          "text": "I've got you down for Thursday at 10 AM. You'll get a text confirmation shortly. Thanks!"
        }
      ],
      "booked": "Thu 10:00 AM · booked"
    }
  },
  "pressurewashing": {
    "badge": "Built for pressure washing pros · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while you're behind the wand.",
      "sub": "Koemori is the AI receptionist built for pressure washing and exterior cleaning companies. It answers every call in under 3 seconds, texts you the lead, and books the job — so the homeowner staring at green siding never ends up calling the next washer instead."
    },
    "missedCall": {
      "value": "$450",
      "label": "average value of a missed exterior-cleaning job",
      "yearLost": "$20,000+"
    },
    "loopDescs": [
      "A homeowner calls about black streaks down the siding or a slick, algae-green deck — and you're behind the machine with the pump roaring and surfactant dwelling on the wall. No way you hear the phone. Koemori picks up in under 3 seconds, in a real human voice, and never lets it ring out.",
      "The second the call ends, you get a text: name, number, address, what they want cleaned, and the full transcript. You already know if it's a quick driveway rinse or a two-story whole-house soft-wash — so you know which tips, surfactant, and ladder to load before you roll.",
      "Koemori asks the right questions, then books their preferred time straight onto your calendar. You pull off this job with the next one already scheduled, instead of returning sun-baked calls after dark and playing phone tag with people who already hired someone else."
    ],
    "qualifyDesc": "Koemori asks what you'd ask: what surface needs cleaning — siding, driveway, deck, fence, gutters, or commercial flatwork — roughly the square footage or number of stories, whether it's a gentle soft-wash or straight pressure, and if they want a one-time clean or a recurring maintenance stop. By the time you read the text, you know exactly what truck, tips, and chemicals to load — and whether it's a $200 driveway or a $1,200 house.",
    "why": {
      "h2Lead": "Built for pressure washing.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$1,200",
          "body": "is what a two-story whole-house soft-wash with the driveway and walks can run. Miss that one call and you didn't lose a rinse — you lost the biggest ticket of the week to whoever picked up."
        },
        {
          "stat": "12x a year",
          "body": "is what a storefront or commercial flatwork account is worth on a recurring plan. One booked maintenance stop becomes a standing route, not a one-off — but only if someone's on the phone to lock it in."
        },
        {
          "stat": "<3s",
          "body": "to answer every call — while you're blasting a driveway, climbing down off the ladder, or dead asleep after a 12-hour day baking in the sun."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 25,
      "missedPct": 50,
      "avgJob": 450,
      "avgJobMin": 150,
      "avgJobMax": 2500,
      "blurb": "Add up the calls you miss every week while you're on the wand. In exterior cleaning, half of them never call back — they book the next washer who picked up, and the recurring accounts walk out the door with them."
    },
    "surge": {
      "badge": "Spring rush · Always on",
      "h2Lead": "When the sun comes out,",
      "h2Accent": "so does the grime.",
      "body": "The first warm week, every homeowner in town suddenly sees the green on their siding, the black streaks on the driveway, and the slime on the deck they want gone before the cookout — and they all call at once. Homes hit the market, HOAs mail out violation letters, graduation and party deadlines stack up. Every missed call in the spring and summer surge is a job that walks to the washer who answered. Koemori handles unlimited calls at once, around the clock, with zero surge fees.",
      "bigStat": "85%",
      "bigStatSub": "of exterior-cleaning demand lands in the spring and summer months",
      "cards": [
        {
          "stat": "0",
          "label": "Missed calls during peak season",
          "sub": "every ring gets a real conversation"
        },
        {
          "stat": "24/7",
          "label": "Answered, including weekends",
          "sub": "when homeowners book before the cookout"
        },
        {
          "stat": "∞",
          "label": "Simultaneous calls handled",
          "sub": "no busy signal during the spring rush"
        },
        {
          "stat": "$0",
          "label": "Surge or overflow fees",
          "sub": "flat price, peak season included"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built for pressure washing and exterior cleaning companies. It answers every inbound call in under 3 seconds, qualifies the lead, books the job, and texts you an instant summary — so you never lose a customer because you were behind the wand with the machine running. If you clean siding, driveways, decks, fences, or commercial flatwork, it's built for you."
      },
      {
        "q": "How does it actually work for a pressure washing business?",
        "a": "When a customer calls your number, Koemori answers immediately — day, night, or weekend. It talks like a real person, asks about the surface, the size or number of stories, and whether they want a gentle soft-wash or straight pressure, books their preferred time, and texts you a full summary with the transcript. No voicemail, no missed calls, no leads slipping to the next washer in the search results."
      },
      {
        "q": "Can it handle both quick driveways and big whole-house soft-wash jobs?",
        "a": "Yes. Koemori sorts a $150 driveway rinse from a $1,200 two-story soft-wash on the same call. It asks about surface, square footage or stories, and one-time versus recurring, so the lead lands on your phone already scoped — you know which tips, surfactant, and ladder to load before you ever roll the truck."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori talks in a natural, friendly human voice — most callers never realize it's AI. It listens, asks the questions a real estimator would ask about surface and square footage, and handles the conversation smoothly. Your customers just feel like they reached a company that actually picks up the phone."
      },
      {
        "q": "Do I have to change my phone number to set it up?",
        "a": "No number changes needed. Setup takes under 5 minutes — you forward your calls to your Koemori number with a simple dial code on your phone. Your existing number stays exactly the same. When you're free, take calls yourself; when you're behind the machine or off the clock, Koemori has it covered."
      },
      {
        "q": "What makes it different from a generic answering service?",
        "a": "Generic services read a script and take a message — they don't know a soft-wash from a straight pressure job, or why you'd never hit older siding or a screen at 4,000 PSI. Koemori is trained on exterior cleaning: it asks about surface type, square footage, and one-time versus recurring maintenance, then books the appointment straight onto your calendar. You get a qualified, scheduled lead, not a sticky note to call back."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Pressure Washing Companies",
      "description": "Koemori answers every pressure washing call in under 3 seconds, texts you the lead, and books the job — so you never lose a soft-wash or driveway to a missed call. Built for exterior cleaning pros."
    },
    "card": {
      "blurb": "The AI receptionist for pressure washing pros — answers every call while you're behind the wand, then texts you the booked job.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "residential house & siding soft-wash",
      "driveways, decks & patio flatwork",
      "commercial flatwork & storefronts",
      "one-time exterior cleaning",
      "recurring maintenance plans"
    ],
    "example": {
      "caller": "Hi, my driveway and the side of my house are covered in green and black streaks — can someone come take a look before this weekend?",
      "outcome": "Soft-wash booked for Friday."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Spotless Pressure Washing, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, my siding and driveway are looking pretty grimy. I'd like to get them washed."
        },
        {
          "speaker": "ai",
          "text": "Happy to help with that. Roughly how big is the area — single-story house, two-story, and how long's the driveway?"
        },
        {
          "speaker": "caller",
          "text": "It's a two-story house and a two-car driveway, maybe forty feet long."
        },
        {
          "speaker": "ai",
          "text": "Got it. I can get a tech out Thursday morning between 9 and 11 — does that work?"
        },
        {
          "speaker": "caller",
          "text": "Thursday morning's perfect."
        },
        {
          "speaker": "ai",
          "text": "Great, you're booked for Thursday, 9 to 11 AM. You'll get a text confirmation shortly."
        }
      ],
      "booked": "Thu 9-11 AM · booked"
    }
  },
  "detailing": {
    "badge": "Built for auto detailers · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while you're elbow-deep in a detail.",
      "sub": "Koemori is the AI receptionist built for auto detailers — mobile and shop. It answers every call in under 3 seconds, sends you the lead, and lines up the appointment, so you never lose a booking while both hands are buried in someone's back seat."
    },
    "missedCall": {
      "value": "$300",
      "label": "average value of a missed detailing booking",
      "yearLost": "$18,000+"
    },
    "loopDescs": [
      "You're mid paint correction, dragging an extractor across a back seat, or buffing under the sun with the polisher screaming — there's no way you hear the phone. Koemori picks up in under 3 seconds in a natural voice and works the caller like your front desk would, instead of letting them hang up and dial the next detailer.",
      "The second the call ends, you get a text: the caller's name, number, the vehicle, the package they asked about, and the full transcript. You know it's a $1,500 ceramic job versus a basic wash before you ever set down the buffer — so you call the big ones back first.",
      "Koemori asks for their preferred day and where they want it — your bay or their driveway — and drops it straight onto your calendar. The customer hangs up booked, not waiting on a callback you'll forget by the time you peel off your gloves."
    ],
    "qualifyDesc": "Koemori asks exactly what you'd ask: what they're driving and the size (sedan, truck, SUV, three-row, van), interior, exterior, or a full detail, whether they want a ceramic coating or paint correction, how rough the inside is — pet hair, spills, smoke — and mobile at their place or drop-off at the shop. A high-ticket coating and a maintenance wash both land on your calendar with a real scope, not a name and a guess.",
    "why": {
      "h2Lead": "Built for detailers.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$1,500+",
          "body": "is what one ceramic coating or multi-stage paint correction can book at. Miss that call mid-buff and the high-ticket job goes to whoever picked up — you can't fit it in next week, they want it now."
        },
        {
          "stat": "$2,400/yr",
          "body": "is what one recurring maintenance client is worth — monthly washes that rebook themselves. Lose them to voicemail once and you lose the whole year of repeat revenue, not a single detail."
        },
        {
          "stat": "Sat + Sun",
          "body": "is when half your bookings come in and both hands are on a vehicle. Koemori answers every weekend, car-show, and wedding-season call while you're heads-down in the bay."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 30,
      "missedPct": 50,
      "avgJob": 300,
      "avgJobMin": 120,
      "avgJobMax": 2500,
      "blurb": "Most detailers miss half their calls — heads-down in a vehicle or slammed on a Saturday. Slide in your numbers and see what those missed details and ceramic jobs are quietly costing you every month."
    },
    "surge": {
      "badge": "Weekend & event season · Always on",
      "h2Lead": "When the calls",
      "h2Accent": "all hit at once.",
      "body": "Spring pollen and road-salt season, wedding and car-show weekends, every Saturday morning — that's when the phone won't stop and you've got a panel half-buffed in front of you. While the detailer across town sends callers to voicemail, you get the booking. Koemori never steps away to rinse off, never clocks out, and never lets a call ring through.",
      "bigStat": "85%",
      "bigStatSub": "of detailing jobs are booked over the phone, not online — so a missed call is a missed detail",
      "cards": [
        {
          "stat": "3x",
          "label": "Call volume in spring",
          "sub": "Pollen, road salt, and tax-refund splurges all land at once"
        },
        {
          "stat": "Sat & Sun",
          "label": "Peak booking days",
          "sub": "When you're slammed and both hands are on a vehicle"
        },
        {
          "stat": "24/7",
          "label": "Always answering",
          "sub": "Nights, weekends, and mid-detail — every call picked up"
        },
        {
          "stat": "$1,500+",
          "label": "Ceramic jobs saved",
          "sub": "The high-ticket call never rolls to voicemail"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built for auto detailers — mobile operators and shop-based crews alike. It answers every inbound call in a natural human voice, captures the lead, and books the appointment for you. It's for any detailer losing jobs because they can't get to the phone with their hands inside a vehicle."
      },
      {
        "q": "How does it actually work for a detailing business?",
        "a": "When a customer calls, Koemori answers in under 3 seconds and talks like a real person. It asks about the vehicle and size, the package they want, whether it's interior, exterior, or a full detail, and mobile versus drop-off, then offers your open times and books them in. The moment the call ends, you get a text with the lead details and the full transcript."
      },
      {
        "q": "How much does it cost compared to a human receptionist?",
        "a": "A part-time front-desk person runs a couple thousand a month plus payroll headaches, and they still go home at night. Koemori is a flat monthly fee — a fraction of that — and it works nights, weekends, and your whole busy season without a break. One booked ceramic coating usually covers the cost for the entire month."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori uses a natural, conversational voice that most callers don't realize is AI. It listens, answers real questions about your packages and pricing, and handles the back-and-forth of picking a time and a location. The goal is a smooth, professional call that gets the customer booked — not a clunky phone tree."
      },
      {
        "q": "Can it quote ceramic coatings and bigger jobs, not just a basic wash?",
        "a": "Yes. Koemori is built to scope the high-ticket work — it asks the questions that separate a quick wash from a ceramic coating or multi-stage paint correction: vehicle size, condition, the package they're after. You get a qualified lead with real scope, so you know which calls to ring back first and what the job is worth before you do."
      },
      {
        "q": "What makes it specific to auto detailing?",
        "a": "Koemori is trained on how detailing calls actually go. It knows to ask about vehicle type and size, interior versus exterior, ceramic coating and paint correction, recurring maintenance plans, and mobile versus drop-off — the questions that turn a call into a real quote. It books a basic wash and a high-ticket coating with the same confidence."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Auto Detailing Shops",
      "description": "Koemori answers every detailing call in under 3 seconds, texts you the lead, and books the appointment — so you never lose a ceramic job or a detail to a missed phone again."
    },
    "card": {
      "blurb": "The AI receptionist for auto detailers — answers every call, captures the lead, and books the detail while your hands are inside a vehicle.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "mobile auto detailing",
      "shop-based detailing",
      "ceramic coating & paint correction",
      "fleet & dealer detailing",
      "interior deep cleaning"
    ],
    "example": {
      "caller": "Hey, I've got a black Tahoe with swirl marks all over the hood and I want it ceramic coated before my daughter's wedding next weekend — can you guys do that?",
      "outcome": "Booked a ceramic coating."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Apex Auto Detailing, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hey, I'd like to get my car detailed inside and out. Maybe ceramic coating too."
        },
        {
          "speaker": "ai",
          "text": "Happy to set that up. What's the year, make, and model?"
        },
        {
          "speaker": "caller",
          "text": "It's a 2021 Honda Accord, midsize sedan."
        },
        {
          "speaker": "ai",
          "text": "Got it. We can do a full interior and exterior detail with ceramic coating. Would you prefer mobile at your place or here at the shop?"
        },
        {
          "speaker": "caller",
          "text": "Mobile would be great, at my house."
        },
        {
          "speaker": "ai",
          "text": "Perfect. I've got you booked for Thursday at 10 AM, mobile service. You'll get a text confirmation shortly."
        }
      ],
      "booked": "Thu 10:00 AM · booked"
    }
  },
  "hvac": {
    "badge": "Built for HVAC pros · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while your gauges are on the unit.",
      "sub": "Koemori is the AI receptionist built for HVAC companies. It answers every call in under 3 seconds, sends you the lead, and lines up the appointment — so the homeowner with a dead AC books with you instead of the contractor who picked up first."
    },
    "missedCall": {
      "value": "$1,800",
      "label": "average value of a missed HVAC call",
      "yearLost": "$45,000+"
    },
    "loopDescs": [
      "You're in a 130-degree attic with your gauges hooked up, or it's 2am on a no-heat run — there's no way you're grabbing the phone. Koemori picks up in under 3 seconds, sounds like a real person, and stays calm with a homeowner whose house just hit 85 inside.",
      "The second the call ends, you get a text with the customer's name, number, a clean summary, and the full transcript. You know if it's a dead capacitor, a frozen coil, or a 15-year-old unit that's finally done — before you ever climb down and call back.",
      "Koemori books their preferred time straight onto your calendar — same-day no-cool, a tune-up, or a sit-down to quote a new system. The call's locked in while you're still pulling vacuum, no phone tag, no callbacks that go nowhere."
    ],
    "qualifyDesc": "Koemori asks what your dispatcher would: is it the AC or the furnace, what's it doing — no air, warm air, no heat, a unit that won't kick on — the make and rough age of the system, whether it's a full no-cool/no-heat emergency or a tune-up that can wait, and whether they're leaning repair or ready to talk replacement. You read the answers before you call back, so you already know if it's a $350 capacitor or a $9,000 changeout.",
    "why": {
      "h2Lead": "Built for HVAC.",
      "h2Accent": "Trained for the trade.",
      "stats": [
        {
          "stat": "$9,000",
          "body": "A single system changeout runs several thousand dollars. Miss that call and the install — plus every future tune-up, repair, and replacement that homeowner needs — walks to the company that answered the phone."
        },
        {
          "stat": "2x",
          "body": "An after-hours no-heat or no-cool call commands an emergency premium most shops never collect, because nobody's awake to answer it. Koemori books those calls at 2am while your competitors sleep."
        },
        {
          "stat": "Years",
          "body": "A maintenance-plan customer is recurring revenue — spring and fall tune-ups, priority repairs, the eventual changeout. Koemori pitches the plan on the call and books it, so that lifetime account doesn't slip to the next contractor."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 35,
      "missedPct": 52,
      "avgJob": 600,
      "avgJobMin": 250,
      "avgJobMax": 9000,
      "blurb": "An HVAC repair runs a few hundred dollars; a full changeout runs several thousand — and a maintenance-plan customer is worth years of recurring work. Do the math on the calls ringing out to voicemail while you're up on a unit."
    },
    "surge": {
      "badge": "First heat wave · Always on",
      "h2Lead": "The first 95-degree day breaks your phone.",
      "h2Accent": "Koemori doesn't.",
      "body": "The first real heat wave and the first hard freeze are the days every system in town quits at once. Your phone rings nonstop while you're already buried under a unit, and every ring you miss is a homeowner sweating it out who just dials the next HVAC company on the list. Koemori answers all of them, sorts the emergencies from the tune-ups, and books the work — no matter how fast they come in.",
      "bigStat": "85%",
      "bigStatSub": "of homeowners with a dead AC or furnace call the next company when no one picks up — they won't leave a voicemail",
      "cards": [
        {
          "stat": "300%+",
          "label": "Call spike",
          "sub": "Inbound calls surge the day the first heat wave or freeze hits"
        },
        {
          "stat": "0",
          "label": "Calls to voicemail",
          "sub": "Every no-cool and no-heat call gets a live answer"
        },
        {
          "stat": "2am",
          "label": "Still answering",
          "sub": "No-heat calls don't wait for business hours — neither does Koemori"
        },
        {
          "stat": "<3s",
          "label": "Pickup speed",
          "sub": "Answered before the homeowner thinks about hanging up"
        }
      ]
    },
    "faq": [
      {
        "q": "What exactly is Koemori, and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for HVAC companies. It answers every inbound call in a natural human voice, texts you the lead the moment the call ends, and books the customer's preferred time on your calendar. It's for owners and small shops that lose jobs every week because nobody can pick up while they're up on a unit or out on a service call."
      },
      {
        "q": "How does it actually work on an HVAC call?",
        "a": "When a customer calls, Koemori answers in under 3 seconds and walks them through it like a real dispatcher — AC or heat, what it's doing, make and age of the system, emergency no-cool/no-heat or a routine tune-up, repair or replace. The second the call ends, you get a text with their name, number, a summary, and the full transcript. If they want service, it books their preferred time straight onto your calendar."
      },
      {
        "q": "Can it sell and book my maintenance plans?",
        "a": "Yes. Koemori is built to know your tune-up and maintenance-plan offers, so when a homeowner calls about a seasonal check or a one-off repair, it can offer the plan, explain what's included, and book the visit. That's recurring revenue — spring and fall tune-ups and priority service — that usually slips through the cracks when you're too busy to pitch it."
      },
      {
        "q": "Is this cheaper than hiring a receptionist or an answering service?",
        "a": "A full-time receptionist costs a salary plus benefits and still goes home at 5pm — right when the after-hours no-heat calls start. An answering service usually just takes a message and charges per call, which gets brutal during a heat wave. Koemori is a flat monthly rate, answers unlimited calls around the clock, and actually books the appointment instead of leaving you a slip to call back."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori uses a natural, conversational human voice, and most callers don't realize they're talking to AI. It listens, responds to what the homeowner actually says, and handles a panicked no-cool call calmly instead of reading a script. It's a far better experience than voicemail, and miles better than a phone that just rings out."
      },
      {
        "q": "How hard is setup, and do I keep my number?",
        "a": "Setup takes about 15 minutes and you keep your existing business number — nothing changes for your customers. You forward your calls to Koemori whenever you want it answering: all the time, after hours, or only when you can't pick up. You tell it your services, your service area, and your hours, and it's live in time for the next heat wave."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for HVAC Companies",
      "description": "Koemori is the AI phone receptionist built for HVAC contractors. It answers every call in under 3 seconds, texts you the lead, and books the appointment — so you never lose a no-cool or no-heat job to a missed call."
    },
    "card": {
      "blurb": "The AI receptionist built for HVAC — answers every no-cool and no-heat call in seconds, texts you the lead, and books the service call while your gauges are still on the unit.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "AC & furnace repair",
      "system installs & replacements",
      "tune-ups & maintenance plans",
      "emergency no-cool / no-heat",
      "indoor air quality"
    ],
    "example": {
      "caller": "My AC's been blowing warm all night and it's already 84 in the house with the baby — can someone come out today?",
      "outcome": "Booked a same-day no-cool visit."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Summit Heating and Air, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hey, my AC just stopped blowing cold air and it's brutal in here."
        },
        {
          "speaker": "ai",
          "text": "Oh no, let's get you taken care of. Is the unit running at all, or totally dead?"
        },
        {
          "speaker": "caller",
          "text": "It's running, just blowing warm air the whole time."
        },
        {
          "speaker": "ai",
          "text": "Got it, sounds like it needs a tech out today. I've got a technician open at 2 PM this afternoon — does that work?"
        },
        {
          "speaker": "caller",
          "text": "Yeah, 2 works great."
        },
        {
          "speaker": "ai",
          "text": "Perfect, you're booked for today at 2 PM. You'll get a text confirmation shortly. Talk soon."
        }
      ],
      "booked": "Today 2:00 PM · booked"
    }
  },
  "plumbing": {
    "badge": "Built for plumbers · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while your head's under the sink.",
      "sub": "Koemori is the AI receptionist built for plumbing companies. It answers every call in under 3 seconds, sends you the lead, and lines up the appointment — so the homeowner standing in a flooding kitchen never hits your voicemail and dials the next plumber."
    },
    "missedCall": {
      "value": "$525",
      "label": "average value of a missed plumbing call",
      "yearLost": "$15,000+"
    },
    "loopDescs": [
      "Your hands are wet, your head's under a vanity, and the phone's ringing in the truck across the yard. Koemori picks up in under 3 seconds in a natural, human voice — so the homeowner watching water spread across the floor talks to someone instead of a beep.",
      "The second the call ends, you get a text: the caller's name, number, what they described — leak, no hot water, backed-up drain, burst pipe — and the full transcript. You know if it's a 2am emergency or a Tuesday faucet swap before you ever wipe your hands.",
      "Koemori asks where the water's coming from, whether it's an emergency or can wait, and books their preferred window straight onto your calendar. You finish the job in front of you with tomorrow already filling in."
    ],
    "qualifyDesc": "Koemori asks the questions a plumbing customer answers anyway: what's wrong (leak, clog, no hot water, sewer backup, no water at all), where in the house it's happening, whether the water is actively running or shut off, and whether it's an emergency or can take a scheduled slot. By the time you read the text, the lead is triaged — burst pipe right now versus a water-heater quote next week — so you know exactly how fast to roll.",
    "why": {
      "h2Lead": "Built for plumbers.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "2x",
          "body": "After-hours and emergency calls bill at premium rates — the burst pipe at midnight is the most profitable job of your week. Those are the exact calls a busy plumber can't answer, and Koemori grabs every one."
        },
        {
          "stat": "$3,500+",
          "body": "A water heater swap, a repipe, or a sewer line is worth thousands. Miss that one call and you don't lose a service fee — you lose the whole ticket to whoever picked up the phone first."
        },
        {
          "stat": "24/7",
          "body": "Plumbing emergencies don't keep business hours. A frozen line at 2am or a flooded basement on Sunday goes to whoever answers — Koemori answers nights, weekends, and holidays so it's always you."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 30,
      "missedPct": 50,
      "avgJob": 525,
      "avgJobMin": 150,
      "avgJobMax": 6000,
      "blurb": "A drain clear is a couple hundred dollars; a repipe or sewer line runs into the thousands. Every call you don't answer is a homeowner with water on the floor dialing the next plumber. Move the sliders to see what those missed calls are quietly costing you each month."
    },
    "surge": {
      "badge": "Freeze season · Always on",
      "h2Lead": "First hard freeze.",
      "h2Accent": "Every pipe in town lets go.",
      "body": "When the temperature drops below freezing, pipes burst and water heaters give out — and every phone in town lights up the same night. That's the week you physically can't answer, because you're already elbow-deep in someone else's flooded basement. Koemori catches every call in the surge, sorts the burst pipes from the dripping faucets, and books the work while your competitors run straight to voicemail.",
      "bigStat": "85%",
      "bigStatSub": "of burst-pipe and no-water calls land during a cold snap — the exact hours you're swamped on another emergency",
      "cards": [
        {
          "stat": "3x",
          "label": "Call volume in a freeze",
          "sub": "Burst pipes and no-water calls spike overnight"
        },
        {
          "stat": "2am",
          "label": "Still answering",
          "sub": "Midnight floods don't wait for business hours"
        },
        {
          "stat": "<3s",
          "label": "Pickup speed",
          "sub": "Even when every line is ringing at once"
        },
        {
          "stat": "0",
          "label": "Calls to voicemail",
          "sub": "Every emergency reaches a real voice"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for plumbing companies. It answers your inbound calls in a natural human voice, texts you the lead, and books appointments on your calendar. It's for owner-operators and small shops who lose jobs every week because they can't get to the phone with their hands under a sink or their head in a crawlspace."
      },
      {
        "q": "How does it work for a plumbing business?",
        "a": "When a customer calls about a leak, a clog, no hot water, or a burst pipe, Koemori answers in under 3 seconds. It figures out what's wrong, where in the house, whether the water is still running, and whether it's an emergency or can be scheduled. The moment the call ends you get a text with the name, number, summary, and transcript, and the customer's preferred time drops straight onto your calendar."
      },
      {
        "q": "Does it handle after-hours emergency calls?",
        "a": "That's where it earns its keep. The midnight burst pipe and the no-hot-water-on-a-Sunday call are your highest-paying jobs, and they're the ones a human receptionist or a 5pm answering service hands to voicemail. Koemori answers nights, weekends, and holidays, flags the true emergencies, and books them — so the premium work doesn't walk to a competitor."
      },
      {
        "q": "How much does it cost compared to a human receptionist?",
        "a": "A full-time receptionist or answering service runs a salary plus benefits, and they still clock out at 5 and miss the midnight burst-pipe call. Koemori is a flat monthly fee — a fraction of that — and it works nights, weekends, and the busiest freeze week of the year without overtime. One water heater job it saves usually covers the month."
      },
      {
        "q": "Does it sound robotic?",
        "a": "No. Koemori talks in a natural, conversational voice — it greets the caller, asks about the problem, and handles basic questions like a calm front-desk person would. Most callers never realize they're talking to AI. The point is the homeowner with water on the floor feels heard, not handed off to a machine."
      },
      {
        "q": "What makes it specific to plumbing?",
        "a": "Koemori already speaks the trade. It knows the difference between a slow drip and a burst main, asks the questions a plumbing customer actually answers — symptom, location, water still running, emergency or scheduled — and triages urgency the way you would. It treats a flooding kitchen as the emergency it is and a faucet swap as the routine it is. It's not a generic call bot with your name on it; it's tuned for how plumbing jobs really come in."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Plumbers | Never Miss a Call",
      "description": "Koemori is the AI phone receptionist built for plumbing companies. Answers every call in under 3 seconds, texts you the lead, and books the job — so you never lose an emergency or a water-heater install to a missed call."
    },
    "card": {
      "blurb": "The AI receptionist for plumbers — answers every leak, clog, and burst-pipe call while your head's under the sink, then books the job.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "residential service & repair",
      "emergency / 24-hour plumbing",
      "water heater & tankless",
      "drain cleaning & sewer",
      "repipes & new construction"
    ],
    "example": {
      "caller": "My water heater's leaking all over the garage floor and there's no hot water — can someone come out today?",
      "outcome": "Booked a same-day emergency visit."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Hometown Plumbing, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, there's water leaking under my kitchen sink and it's getting all over the floor."
        },
        {
          "speaker": "ai",
          "text": "Oh no, sorry to hear that. Is it actively spraying or dripping right now, or were you able to shut the valve off?"
        },
        {
          "speaker": "caller",
          "text": "I turned the little valve under the sink, so it stopped for now."
        },
        {
          "speaker": "ai",
          "text": "Perfect, that buys us time. I can get a tech out today between two and four. Does that work?"
        },
        {
          "speaker": "caller",
          "text": "Yeah, two to four is great."
        },
        {
          "speaker": "ai",
          "text": "Done — you're booked for today, two to four. We'll text you when he's on the way."
        }
      ],
      "booked": "Today 2-4 PM · booked"
    }
  },
  "electrical": {
    "badge": "Built for electricians · Answering while your hands are in the panel",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while your hands are in the panel.",
      "sub": "Koemori is the AI receptionist built for electrical contractors. It answers every call in under 3 seconds, texts you the lead, and books the service call — so the homeowner with a dead breaker never hangs up and dials the next licensed electrician."
    },
    "missedCall": {
      "value": "$450",
      "label": "average value of a missed electrical service call",
      "yearLost": "$16,000+"
    },
    "loopDescs": [
      "Your phone rings while you're up a ladder with both hands in a live panel, a wire stripped and the main shut off — there's no way you're answering. Koemori picks up in under 3 seconds in a natural human voice, so the caller with a tripping breaker or a half-dark house talks to a real-sounding person instead of your voicemail.",
      "The second the call ends, you get a text with the caller's name, number, what's wrong, and the full transcript. You know whether it's a no-power emergency, a panel that keeps tripping, or a quote for an EV charger before you ever wipe your hands and call back.",
      "Koemori books the customer's preferred time straight onto your calendar — service call, panel upgrade, EV charger, generator install, or a lighting and outlet job. The appointment is locked in while you finish the work in front of you, so tomorrow's already filling itself."
    ],
    "qualifyDesc": "Koemori asks the questions you'd ask before rolling a truck: Is anything sparking, buzzing, or smelling like burning plastic? Is the whole house dark or just one circuit? Is a breaker tripping over and over, or did the power just drop? Is this a repair, a panel or service upgrade, an EV charger, a generator, or new lighting and outlets? By the time you call back, you already know if it's a safety emergency you drop everything for, a five-minute fix, or a half-day install worth thousands.",
    "why": {
      "h2Lead": "Built for electricians.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$4,000+",
          "body": "is what a panel upgrade, service change, or whole-home generator can run — the high-ticket jobs that come in by phone. Miss that one call and it doesn't roll to voicemail, it rolls to the next electrician's truck."
        },
        {
          "stat": "1 in 3",
          "body": "service calls turn into bigger work once you're on site — a code correction, an added circuit, a panel that's overdue. Booking the first visit is how you win the repeat ticket, not just the trip fee."
        },
        {
          "stat": "24/7",
          "body": "burning-smell, sparking-outlet, and no-power calls don't keep business hours. Koemori answers nights, weekends, and the middle of a heat wave, when the urgent calls — and the biggest jobs — actually come in."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 35,
      "missedPct": 45,
      "avgJob": 450,
      "avgJobMin": 150,
      "avgJobMax": 6000,
      "blurb": "Count the calls that roll to voicemail while you're wiring a panel or driving between sites. In electrical, one of those could be a $4,000 panel upgrade — and the homeowner books whoever picks up first."
    },
    "surge": {
      "badge": "Outage season · Always on",
      "h2Lead": "Heat waves and outages",
      "h2Accent": "light up every phone at once.",
      "body": "When the grid drops in a storm or a heat wave overloads it, every phone in your service area rings at the same time. Generator installs, tripped panels, dead AC circuits, and half-lit houses flood in faster than any one person can answer — and that's exactly when the jobs are biggest and the calls go to voicemail. Koemori answers every one, flags the burning-smell emergencies first, and books the rest.",
      "bigStat": "85%",
      "bigStatSub": "of outage-day callers hire the first electrician who actually picks up the phone",
      "cards": [
        {
          "stat": "10x",
          "label": "call volume",
          "sub": "during a regional outage or heat-wave grid strain"
        },
        {
          "stat": "<3s",
          "label": "pickup speed",
          "sub": "every call, even when ten ring at once"
        },
        {
          "stat": "0",
          "label": "missed leads",
          "sub": "while competitors run straight to voicemail"
        },
        {
          "stat": "24/7",
          "label": "always answering",
          "sub": "nights, weekends, holidays, peak load"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for electrical contractors. It answers every inbound call in a natural human voice, captures the lead, and books the appointment on your calendar. It's for the electrician who's too deep in a panel or a crawlspace to grab the phone — and tired of losing panel upgrades, EV chargers, and generator installs to voicemail."
      },
      {
        "q": "How does it work for an electrical business?",
        "a": "When a customer calls, Koemori picks up in under 3 seconds and talks like a real receptionist. It finds out whether it's a no-power emergency, a breaker that keeps tripping, a sparking outlet, or a quote for a new install, checks for safety urgency like a burning smell, then asks about the type of work. The moment the call ends, it texts you the name, number, summary, and full transcript, and books their preferred time on your calendar."
      },
      {
        "q": "Will it flag a real safety emergency, or treat everything the same?",
        "a": "It triages. Koemori is tuned to listen for the words that mean drop everything — burning smell, smoke, sparking, a panel that's hot to the touch, no power to half the house. It marks those calls urgent in the text it sends you so a true emergency never sits in line behind a routine lighting quote. You see the dangerous ones first."
      },
      {
        "q": "How does the cost compare to a human receptionist?",
        "a": "A full-time receptionist runs thousands a month and still goes home at 5, calls in sick, and can't answer two phones at once when an outage hits. Koemori costs a fraction of that, never misses a shift, and handles every call at the same time. One booked panel upgrade or generator install usually covers it for a long stretch."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori uses a natural, human-sounding voice and conversational timing — most callers don't realize it isn't a person. It speaks plainly, stays calm with a homeowner whose power just dropped, and asks the right electrical questions instead of reading a stiff script. Your customers feel taken care of, not handed off to a machine."
      },
      {
        "q": "What makes it specific to electrical work?",
        "a": "Koemori is tuned to the way homeowners describe electrical problems — no power, breakers tripping, outlets sparking, lights flickering, a burning smell — and it knows to flag safety urgency right away. It asks about the jobs you actually do: service and repair, panel and service upgrades, lighting and outlets, EV chargers, and generators. It's not a generic answering service with your name pasted on; it talks like it works in the trade."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Electricians & Electrical Contractors",
      "description": "Koemori is the AI phone receptionist for electricians. Answers every call in under 3 seconds, flags safety emergencies, texts you the lead, and books the service call — so you never lose a panel upgrade or generator install to a missed phone."
    },
    "card": {
      "blurb": "The AI receptionist that answers every call while your hands are in the panel — flags the emergencies, texts you the lead, and books the job.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "residential service & repair",
      "panel & service upgrades",
      "EV charger installs",
      "generator installs",
      "commercial electrical"
    ],
    "example": {
      "caller": "My kitchen outlets just died and there's a faint burning smell coming from the panel — can someone come out today?",
      "outcome": "Flagged urgent, same-day visit booked."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Bright Spark Electric, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Yeah, my kitchen breaker keeps tripping, and I'm thinking I might need a panel upgrade or an EV charger put in."
        },
        {
          "speaker": "ai",
          "text": "Got it. Quick safety check — is the breaker tripping right now, or any burning smell or warm outlets?"
        },
        {
          "speaker": "caller",
          "text": "No smell, it's reset for now, but it trips again every time I run the microwave."
        },
        {
          "speaker": "ai",
          "text": "Okay, that's not an emergency, but worth a look soon. I can get an electrician out to assess the panel and the charger. Does tomorrow afternoon work?"
        },
        {
          "speaker": "caller",
          "text": "Tomorrow afternoon's perfect."
        },
        {
          "speaker": "ai",
          "text": "Great — you're booked for Tuesday at 2:00 PM. We'll text you a confirmation. Thanks for calling!"
        }
      ],
      "booked": "Tue 2:00 PM · booked"
    }
  },
  "garagedoors": {
    "badge": "Built for garage door pros · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while you're winding a torsion spring.",
      "sub": "Koemori is the AI receptionist built for garage door companies. It answers every call in under 3 seconds, sends you the lead, and lines up the service call — so a homeowner with a snapped spring and a car stuck inside never dials the next door company instead."
    },
    "missedCall": {
      "value": "$425",
      "label": "average value of a missed garage door call",
      "yearLost": "$22,000+"
    },
    "loopDescs": [
      "Snapped spring, dead opener, or a car trapped behind a door that won't budge — your hands are on the winding bars and there's no way you grab the phone. Koemori picks up in under 3 seconds in a natural human voice, so the caller never hits voicemail and dials the next door company on the list.",
      "The second the call ends you get a text: name, number, single or double door, what failed, and the full transcript. You've sized up the job — a quick spring swap or a full opener replacement — before you've set the winding bars down.",
      "Koemori books the customer's preferred time straight onto your calendar — same-day spring emergency or a scheduled tune-up. You roll up to a confirmed appointment instead of playing phone tag from under the next door."
    ],
    "qualifyDesc": "Koemori asks what a real garage door call needs: what failed (broken spring, snapped cable, opener won't run, door off the track, grinding rollers), whether it's a single or double door, if a car or the homeowner is trapped inside, and how fast they need a tech rolling. You get the full picture — a $250 spring job or a $2,000 door replacement — before you ever pick up a wrench.",
    "why": {
      "h2Lead": "Built for garage doors.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$1,800+",
          "body": "A new door install runs four figures, and every spring and opener customer is a repeat door buyer down the road. Miss that first ring and you lose the whole ticket — plus the replacement years later — to whoever picked up."
        },
        {
          "stat": "2x",
          "body": "the rate you can charge on an after-hours trapped-car call — the highest-margin job you run. Those calls come in at 6am and 11pm, exactly when nobody's at a desk to grab the line."
        },
        {
          "stat": "<3s",
          "body": "to answer every call, day or night, while both hands are locked on the winding bars. The homeowner staring at a busted spring hears a real voice, not a beep."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 35,
      "missedPct": 45,
      "avgJob": 425,
      "avgJobMin": 150,
      "avgJobMax": 2500,
      "blurb": "Every missed call is a spring repair, opener swap, or new door install going to whoever answered first. Slide your numbers and see what those rings are really worth."
    },
    "surge": {
      "badge": "Cold snap · Always on",
      "h2Lead": "When the cold snaps springs,",
      "h2Accent": "your phone won't stop.",
      "body": "The first hard freeze is brutal on torsion springs — they snap by the dozen across town in the same 48 hours, half of them with a car trapped inside and no way out. That's the week one person at a desk physically can't keep up with the phone. Koemori answers every call instantly, no matter how many ring at the same time, and books the emergencies before they call anyone else.",
      "bigStat": "85%",
      "bigStatSub": "of cold-snap spring failures hit within the same 48 hours",
      "cards": [
        {
          "stat": "0",
          "label": "calls to voicemail",
          "sub": "even when ten ring at once"
        },
        {
          "stat": "24/7",
          "label": "first-freeze coverage",
          "sub": "6am breaks, 11pm trapped cars"
        },
        {
          "stat": "<3s",
          "label": "pickup, every time",
          "sub": "while you're winding a spring"
        },
        {
          "stat": "100%",
          "label": "leads texted to you",
          "sub": "name, door type, transcript"
        }
      ]
    },
    "faq": [
      {
        "q": "What exactly is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for garage door companies. It answers every inbound call in a natural human voice, texts you the lead, and books the appointment on your calendar. It's made for the owner-operator and small shop that can't be on the phone while winding a torsion spring or out on a service call."
      },
      {
        "q": "How does it actually work on a garage door call?",
        "a": "When a customer calls about a broken spring, a dead opener, or a door stuck with their car inside, Koemori picks up in under 3 seconds. It asks the right questions — what failed, single or double door, whether anyone's trapped, how urgent — then texts you the name, number, summary, and full transcript the moment the call ends. If they want to book, it drops their preferred time straight onto your calendar."
      },
      {
        "q": "Can it tell an emergency from a routine call?",
        "a": "Yes. A car trapped behind a stuck door or a spring that snapped before work gets flagged as the emergency it is, so you can roll a truck fast and charge the after-hours rate. A tune-up or a quote on a new door gets scheduled into your normal slots. You see the urgency in the text before you ever call back."
      },
      {
        "q": "Is this cheaper than hiring a receptionist or answering service?",
        "a": "A lot cheaper. A full-time receptionist runs thousands a month and still clocks out at 5pm, and generic answering services can't tell a torsion spring from an extension spring or a cable off the drum. Koemori works every hour for a flat monthly rate and never misses the after-hours emergency calls that are worth the most."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori answers in a natural, conversational human voice — most callers don't realize they're talking to AI. It handles a panicked homeowner with a car trapped behind a stuck door just as smoothly as a routine tune-up request, so your shop sounds professional on every call."
      },
      {
        "q": "What makes it built for garage doors specifically?",
        "a": "Koemori knows the trade. It speaks to broken springs, snapped cables, opener repairs, off-track doors, new installs, and tune-ups, and it treats a car trapped in the garage as the emergency it is. It asks the questions a real garage door customer needs to answer — single or double door, what failed, who's stuck — not a generic script that fumbles the job."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Garage Door Companies",
      "description": "Koemori answers every garage door call in under 3 seconds, texts you the lead, and books the job. Never lose a broken-spring emergency or new door install to a missed call."
    },
    "card": {
      "blurb": "The AI receptionist for garage door pros — answers every broken-spring and trapped-car call, texts you the lead, and books the job while you're winding a spring.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "spring & cable repair",
      "opener repair & install",
      "new door installation",
      "emergency trapped-car calls",
      "tune-ups & maintenance"
    ],
    "example": {
      "caller": "My garage door went up halfway, made a loud bang, and now it won't move and my car's stuck inside — I need someone out today.",
      "outcome": "Booked a same-day emergency visit."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Precision Garage Doors, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, my garage door won't open and my car's stuck inside. I think the spring snapped."
        },
        {
          "speaker": "ai",
          "text": "Oh no, let's get you sorted fast. Is the door fully shut, or is it stuck partway open?"
        },
        {
          "speaker": "caller",
          "text": "It's all the way down. I heard a loud bang this morning and now it won't budge."
        },
        {
          "speaker": "ai",
          "text": "Sounds like a broken spring, that's a same-day fix for us. I can get a tech out today between 2 and 4. Does that work?"
        },
        {
          "speaker": "caller",
          "text": "Yes, please, anything to get my car out."
        },
        {
          "speaker": "ai",
          "text": "Perfect, you're booked for today, 2 to 4 PM. We'll text you when the tech's on the way."
        }
      ],
      "booked": "Today 2-4 PM · booked"
    }
  },
  "pestcontrol": {
    "badge": "Built for pest control pros · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "while you're suited up on the route.",
      "sub": "Koemori is the AI receptionist built for pest control companies. It answers every call in under 3 seconds, texts you the lead, and books the treatment — so the homeowner panicking over a wasp nest or a roach in the kitchen never ends up dialing the next exterminator instead."
    },
    "missedCall": {
      "value": "$320",
      "label": "average value of a missed pest control call",
      "yearLost": "$16,000+"
    },
    "loopDescs": [
      "Wasps in the eaves, roaches behind the fridge, a rat in the garage — pest calls come in panicked and they come in all day. You're suited up mid-treatment or backed into a crawlspace with a respirator on, no way to grab the phone. Koemori picks up every one in a calm, natural voice before it ever rings out to voicemail.",
      "The second the call ends, you get a text with the caller's name, number, the pest, the address, and the full transcript. You finish one stop already knowing exactly what the next one needs — whether to load wasp gear or bring bait stations.",
      "Koemori asks when works and books them straight onto your calendar — a first inspection or a recurring quarterly service — so your route fills itself while your hands are full. Every quarterly account it locks in is recurring revenue, not a one-and-done treatment."
    ],
    "qualifyDesc": "Koemori asks what actually matters on a pest call: what they've got (ants, roaches, rodents, termites, wasps, bed bugs), how bad it's gotten, whether they want a one-time treatment or a recurring quarterly plan, and whether there are kids or pets in the home. By the time you read the text, you know if it's a quick knockdown or a real account worth keeping on the books.",
    "why": {
      "h2Lead": "Built for pest control.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$1,500/yr",
          "body": "is what one recurring quarterly account is worth — year after year. The call that signs that customer can't roll to voicemail, because you're not missing one treatment, you're missing the whole subscription."
        },
        {
          "stat": "$2,500+",
          "body": "is what a single termite or WDO job can run. Miss that inspection call and a competitor's tech is the one walking the foundation instead of you."
        },
        {
          "stat": "<3s",
          "body": "to answer, every time — suited up on a route, under a house in a crawlspace, or fielding a 10pm bed bug panic. The caller gets a real-sounding voice, not a beep."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 35,
      "missedPct": 50,
      "avgJob": 320,
      "avgJobMin": 150,
      "avgJobMax": 2500,
      "blurb": "Add up the calls that roll to voicemail while you're suited up on a route or under a house. In pest control a missed call isn't just one treatment — it's a quarterly account that signs with a competitor instead, every quarter, all year."
    },
    "surge": {
      "badge": "Spring & summer surge · Always on",
      "h2Lead": "When the bugs wake up,",
      "h2Accent": "the phone never stops.",
      "body": "Spring and summer is when ants march in, mosquitoes take over the backyard, and every wasp nest in town gets noticed at once. The calls pile up faster than one person can answer them — and that's exactly when each one is most likely to become a recurring account. Koemori catches every single one while your competitors send callers to voicemail.",
      "bigStat": "85%",
      "bigStatSub": "of new pest control accounts are won during the spring and summer rush — the season that fills your route for the rest of the year",
      "cards": [
        {
          "stat": "3x",
          "label": "call volume in peak season",
          "sub": "Spring and summer can triple your inbound calls overnight"
        },
        {
          "stat": "24/7",
          "label": "after-hours coverage",
          "sub": "Bed bug and wasp panics don't wait for business hours"
        },
        {
          "stat": "0",
          "label": "calls to voicemail",
          "sub": "Every ring gets a real voice, even mid-treatment"
        },
        {
          "stat": "<3s",
          "label": "to answer",
          "sub": "Faster than you could peel off your gloves and grab the phone"
        }
      ]
    },
    "faq": [
      {
        "q": "What exactly is Koemori?",
        "a": "Koemori is an AI phone receptionist built specifically for pest control companies. It answers your inbound calls in a natural human voice, captures the lead and texts it straight to you, and books the customer's preferred time on your calendar. It's made for owner-operators and small crews who can't grab every call because they're suited up out on a route."
      },
      {
        "q": "How does it work for a pest control business?",
        "a": "You forward your business line to Koemori. When a customer calls, it answers in under 3 seconds, asks about the pest, the severity, and whether they want a one-time treatment or a recurring quarterly plan, then books them in. The moment the call ends you get a text with the name, number, address, pest, and full transcript so you show up loaded for the right job."
      },
      {
        "q": "Is it cheaper than a human receptionist?",
        "a": "Far cheaper. A full-time receptionist runs you thousands a month plus payroll and breaks, and still only covers business hours. Koemori works around the clock for a flat monthly rate. Sign just one quarterly account it would've otherwise missed and it's paid for itself for the year — and that account keeps billing every quarter after."
      },
      {
        "q": "Does it sound robotic?",
        "a": "No. Koemori speaks in a warm, natural voice and holds a real conversation — most callers never realize they're not talking to your office. It stays calm and reassuring to someone who just found roaches or bed bugs, asks the right questions about the pest and the home, and never rushes them off the phone."
      },
      {
        "q": "Do I have to change my phone number or setup?",
        "a": "No. You keep your existing business number — you simply forward your calls to Koemori, and you can turn forwarding on and off whenever you want. Setup takes a few minutes and nothing about your current number, trucks, or marketing has to change."
      },
      {
        "q": "What makes it specific to pest control?",
        "a": "Koemori is trained on how pest control calls actually go. It knows the difference between a one-time treatment and a quarterly plan, asks about general pest, rodents, termites, and mosquitoes, handles urgent infestations like wasps and bed bugs, and always checks on kids and pets before recommending service. It's built to protect your recurring revenue, not just take a message."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Pest Control Companies",
      "description": "Koemori answers every pest control call in under 3 seconds, texts you the lead, and books the treatment — so you never lose a quarterly account to a missed call while you're on a route."
    },
    "card": {
      "blurb": "The AI receptionist for pest control. It answers every call, texts you the lead, and books the treatment while you're suited up out on a route.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "general pest & recurring plans",
      "rodent & wildlife control",
      "termite & WDO inspections",
      "mosquito & outdoor control",
      "bed bug & emergency infestations"
    ],
    "example": {
      "caller": "Hi, I just saw two roaches in my kitchen this morning and there's no way I can sleep here tonight — how soon can someone come spray?",
      "outcome": "Booked a same-day treatment."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling Apex Pest Control, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, we've got ants all over the kitchen counter. It's getting bad."
        },
        {
          "speaker": "ai",
          "text": "Ugh, kitchen ants are the worst. Are you looking for a one-time treatment, or an ongoing plan to keep them away?"
        },
        {
          "speaker": "caller",
          "text": "Let's do the recurring plan, I don't want them coming back."
        },
        {
          "speaker": "ai",
          "text": "Smart call. I can get a tech out for your first treatment Thursday at 10 AM. Does that work?"
        },
        {
          "speaker": "caller",
          "text": "Yeah, Thursday morning is perfect."
        },
        {
          "speaker": "ai",
          "text": "Great, you're booked for Thursday at 10 AM to start your plan. We'll see you then!"
        }
      ],
      "booked": "Thu 10:00 AM · booked"
    }
  },
  "landscaping": {
    "badge": "Built for landscapers · On the line 24/7",
    "hero": {
      "h1Lead": "Answers every call",
      "h1Accent": "with both hands in the dirt.",
      "sub": "Koemori is the AI receptionist built for landscaping companies. It answers every call in under 3 seconds, sends you the lead, and lines up the site walk — so the homeowner pricing a paver patio books with you instead of the next crew that picked up."
    },
    "missedCall": {
      "value": "$650",
      "label": "average value of a missed landscaping lead",
      "yearLost": "$20,000+"
    },
    "loopDescs": [
      "A homeowner calls about a paver patio while you're running the plate compactor and your phone's buried in the truck. Koemori picks up in under 3 seconds in a natural voice — no voicemail, no ringing out, no big install handed to the crew that answered first.",
      "The second the call ends, you get a text: name, number, what they want, and the full transcript. A retaining wall, a drainage fix, a fall cleanup — you can tell the five-figure build from the mulch top-off before you've packed up the truck.",
      "Koemori books their preferred time straight onto your calendar for the site walk or design consult. You roll up to a scheduled estimate instead of chasing a callback that lands in their voicemail now too."
    ],
    "qualifyDesc": "Koemori asks exactly what you would: is this a design and install, hardscaping like a patio, retaining wall, or paver walkway, drainage or irrigation, or a seasonal cleanup? It pins down the property size, the rough scope, the timeline they're working toward, and a budget range — so a five-figure install lands on your calendar already sorted from a quick mulch drop, and your site walks aren't wasted on tire-kickers.",
    "why": {
      "h2Lead": "Built for landscapers.",
      "h2Accent": "Not for demos.",
      "stats": [
        {
          "stat": "$12k+",
          "body": "is what one hardscape or full design install can run. The call that lands it sounds exactly like the one for a $200 mulch job — miss it and the whole build walks to whoever answered."
        },
        {
          "stat": "$0",
          "body": "extra to keep a customer who already trusts you. A booked install becomes the spring cleanup, the irrigation tune-up, the next phase — Koemori catches the call that starts years of repeat work on the same yard."
        },
        {
          "stat": "<3s",
          "body": "to pick up, in a natural human voice, while you're on the skid steer or setting pavers and there's no way you'd hear the phone ring over the machine."
        }
      ]
    },
    "roi": {
      "callsPerWeek": 20,
      "missedPct": 50,
      "avgJob": 4500,
      "avgJobMin": 300,
      "avgJobMax": 25000,
      "blurb": "Landscaping jobs swing from a small cleanup to a five-figure hardscape build — and you can't tell which is calling while you're on a machine. Drag the slider to your average job and see what those missed calls are quietly costing you every year."
    },
    "surge": {
      "badge": "Spring & fall rush · Always on",
      "h2Lead": "Spring and fall rush.",
      "h2Accent": "Always on.",
      "body": "When the weather breaks, every homeowner wants their beds redone, a new patio poured, and the yard cleaned up — all at once. Your phone rings off the hook the exact weeks your whole crew is buried on job sites and nobody's near a phone. While your competitors go to voicemail, you get the project.",
      "bigStat": "3x",
      "bigStatSub": "the call volume hits in peak weeks — right when no one on the crew is free to answer",
      "cards": [
        {
          "stat": "3x",
          "label": "Call volume in peak weeks",
          "sub": "Spring kickoff and fall cleanup season bury you in inbound calls"
        },
        {
          "stat": "0",
          "label": "Calls sent to voicemail",
          "sub": "Every ring answered, even with the whole crew in the field"
        },
        {
          "stat": "24/7",
          "label": "After-hours coverage",
          "sub": "Evening and weekend planners book the site walk themselves"
        },
        {
          "stat": "100%",
          "label": "Leads texted to you",
          "sub": "Name, scope, and transcript hit your phone the second each call ends"
        }
      ]
    },
    "faq": [
      {
        "q": "What is Koemori and who is it for?",
        "a": "Koemori is an AI phone receptionist built specifically for landscaping companies. It answers every inbound call in a natural human voice, texts you the lead the moment the call ends, and books the customer's preferred time on your calendar. It's for owners and crews who are out on job sites all day and losing real work every time the phone goes unanswered."
      },
      {
        "q": "How does it actually work for a landscaping business?",
        "a": "When a customer calls, Koemori picks up in under 3 seconds and talks like a real person. It figures out whether they want a design and install, hardscaping, drainage, irrigation, or a cleanup, gathers the scope, timeline, and budget, and lines up a site walk or design consult on your calendar. You get a text with their name, number, a summary, and the full transcript before you've even climbed off the skid steer."
      },
      {
        "q": "Can it tell a big install lead from a small cleanup?",
        "a": "That's the point. Koemori asks about the project, the property size, the timeline, and a budget range, so the text you get tells you at a glance whether it's a five-figure hardscape worth dropping everything for or a quick mulch top-off you can slot in later. You walk into every callback already knowing what the job is worth."
      },
      {
        "q": "Is it cheaper than hiring a receptionist?",
        "a": "Far cheaper. A full-time receptionist runs you thousands a month plus benefits, takes lunch breaks, and goes home at five — right when evening planners are calling about next season's patio. Koemori answers every call around the clock for a flat monthly fee, and a single booked install usually covers the cost for the whole year."
      },
      {
        "q": "Will it sound like a robot to my customers?",
        "a": "No. Koemori speaks in a natural, warm human voice and handles a real back-and-forth conversation. Most callers never realize they're not talking to someone in your office. It stays calm and professional whether it's a quick irrigation question or a big design build the homeowner has been planning for years."
      },
      {
        "q": "What makes it specific to landscaping?",
        "a": "Koemori is trained on how landscaping calls actually go. It knows the difference between a design build, a hardscape install, drainage work, irrigation, and a seasonal cleanup, and it asks about property size, scope, timeline, and budget the way you would. It's tuned for your spring and fall rush, not a generic call script — so the leads it sends are ready to walk and quote."
      }
    ],
    "seo": {
      "title": "Koemori — AI Receptionist for Landscaping Companies",
      "description": "Koemori answers every landscaping call in under 3 seconds, texts you the lead, and books the site walk on your calendar — so you never lose a hardscape or design job to a missed phone."
    },
    "card": {
      "blurb": "Answers every call with your hands in the dirt, sends you the lead, and books the site walk — from a quick cleanup to a five-figure hardscape build.",
      "statV": "<3s",
      "statL": "Pickup speed"
    },
    "tradeOptions": [
      "design & install",
      "hardscaping (patios, walls, pavers)",
      "drainage & irrigation",
      "seasonal cleanups",
      "planting & sod"
    ],
    "example": {
      "caller": "Hey, I've got a sloped backyard that floods every time it rains and I'm thinking a retaining wall with a paver patio up top — can someone come take a look and give me a price?",
      "outcome": "Booked an on-site design consult."
    },
    "demo": {
      "turns": [
        {
          "speaker": "ai",
          "text": "Thanks for calling GreenScape Landscaping, this is Ava. How can I help?"
        },
        {
          "speaker": "caller",
          "text": "Hi, our backyard's a mess. We want a paver patio put in, and maybe some new beds along the fence."
        },
        {
          "speaker": "ai",
          "text": "Love it. Roughly how big a space are we talking for the patio?"
        },
        {
          "speaker": "caller",
          "text": "I'd say maybe fifteen by twenty feet, off the back door."
        },
        {
          "speaker": "ai",
          "text": "Perfect. We'll send a designer out to measure and talk options. Does Thursday at 10 AM work?"
        },
        {
          "speaker": "caller",
          "text": "Thursday at ten is great."
        },
        {
          "speaker": "ai",
          "text": "Done. You're booked for the on-site consult Thursday at 10 AM. We'll see you then!"
        }
      ],
      "booked": "Thu 10:00 AM · booked"
    }
  }
};
